config/routes.rb
Rails.application.routes.draw do
  resources :markets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market.rb
class Market < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = Market.all
  end

  def new
    @market = Market.new
  end

  def create
    @market = Market.new(params.required(:market).permit(:name, :address, :prodcut, :price))
    if @market.save
      redirect_to markets_path
    else
      render :new
    end
  end

  def show
    @market = Market.find(params[:id])
  end

  def edit
    @market = Market.find(params[:id])
  end

  def update
    @market = Market.find(params[:id])
    if @market.update(params.required(:market).permit(:name, :address, :product, :price))
      redirect_to markets_path
    else
      render :new
  end
  end

  def destroy
    @market = Market.find(params[:id])
    if @market.delete
      redirect_to markets_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/_form.html.erb
<%= form_for market do |form| %>

  <div class="field form-group">
    <%= form.text_field :name, class: "form-control", placeholder: "FullName", required: true %>
  </div>
  <div class="field form-group">
    <%= form.text_field :address, class: "form-control", placeholder: "Address", required: true %>
  </div>
  <div class="field form-group">
    <%= form.text_field :product, class: "form-control", placeholder: "Product", required: true %>
  </div>
  <div class="field form-group">
    <%= form.text_field :price, class: "form-control", placeholder: "Price", required: true %>
  </div>

    <div class="actions">
    <%= form.submit class: "btn btn-secondary"%>
    </div><br/>
<% end %>

app/views/markets/edit.html.erb
<h1> Edit </h1>

<%= render 'form', market: @market %>


<%= link_to 'back', markets_path %>

app/views/markets/index.html.erb
<h1> Team Bee </h1>

<table>

  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Product</th>
      <th>Price</th>
    </tr>
  </thead>

  <% @markets.each do |market|%>
 
  <tr>
  <td><%= market.name %></td>
  <td><%= market.address %></td>
  <td><%= market.product %></td>
  <td><%= market.price %></td>
  <td><%= link_to 'Show', market_path(market) %></td>
  <td><%= link_to 'Edit', edit_market_path(market) %></td>
  <td><%= link_to 'Delete', market_path(market), method: :delete, data:{confirm: "warning"} %></td>
  <%end%>
  </tr>
</table>
  </br>
  <%= link_to 'Add New', new_market_path %>

app/views/markets/new.html.erb
<h1> Add </h1>

<%= render 'form', market: @market %>


<%= link_to 'BACK', markets_path %>

app/views/markets/show.html.erb
<p>

<strong>Name</strong>
<strong>Address</strong>
<strong>Product</strong>
<strong>Price</strong>

</p>

<%= @market.name %>
<%= @market.address %>
<%= @market.product %>
<%= @market.price %>

</br>
<%= link_to 'back', markets_path %>